name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-x86:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true

    - name: Build
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu
        tar -czf anypay-websockets-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-gnu/release anypay-websockets
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          anypay-websockets-linux-x86_64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: anypay-websockets-linux-x86_64
        path: target/x86_64-unknown-linux-gnu/release/anypay-websockets

  build-linux-aarch64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        override: true

    - name: Build
      run: |
        cargo build --release --target aarch64-unknown-linux-gnu
        tar -czf anypay-websockets-linux-aarch64.tar.gz -C target/aarch64-unknown-linux-gnu/release anypay-websockets
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          anypay-websockets-linux-aarch64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: anypay-websockets-linux-aarch64
        path: target/aarch64-unknown-linux-gnu/release/anypay-websockets 
